de = input('Enter grade for Differential Equation: ');
cp = input('Enter grade for Computer Programming ');
cpL = input('Enter grade for Computer Programming Lab: ');
cs1 = input('Enter grade for Circuit and System 1: ');
cs1L = input('Enter grade for Circuit and System 1 Lab: ');
cps = input('Enter grade for Communication and Presentation Skills: ');
edg = input('Enter grade for Engineering Drawing and CAD: ');
edgL = input('Enter grade for Engineering Drawing and CAD Lab: ');
ps = input('Enter grade for Pakistan Studies: ');
fprintf('Differential Equation: %s', de, ' 3.33');disp(' ');
fprintf('Computer Programming: %s', cp, ' 3.67');disp(' ');
fprintf('Computer Programming Lab: %s', cpL, ' 3.67');disp(' ');
fprintf('Circuit and System 1: %s', cs1, ' 3.33');disp(' ');
fprintf('Circuit and System 1 Lab: %s', cs1L, ' 3.00');disp(' ');
fprintf('Communication and Presentation Skills: %s', cps, ' 2.67');disp(' ');
fprintf('Engineering Drawing and CAD: %s', edg, ' 3.33');disp(' ');
fprintf('Engineering Drawing and CAD Lab: %s', edgL, ' 3.33');disp(' ');
fprintf('Pakistan Studies: %s', ps, ' 3.00');disp(' ');
CGPA = ((3.33 + 3.67 + 3.33)*3 + (3.67 + 3.33 + 3.00) + (3.00 + 2.67 + 3.33)*2)/18;
fprintf('CGPA is: %i' , CGPA);