n=0:1/10:10;
k=5;
a=pi/2;
x=k * exp(a*n*1i);
c = conj(x);
subplot(2,1,1);
stem(n, real(c));
title('Real part of Exponential Signal');
xlabel('Sample Number');
ylabel('Signal Amplitude');
subplot(2,1,2);
stem(n, imag(c));
title('Imaginary part of Exponential Signal');
xlabel('Sample Number');
ylabel('Signal Amplitude');
