n = -10:0.5:10;
y = exp(-0.2+0.5j)*n;
mag = abs(y);
pha = angle(y);
im_part = imag(y);
re_part = real(y);
subplot(4,1,1);
stem(n, mag);
title('Magnitude of exp\^(-0.2+0.5j)*n Signal');
xlabel('Sample Number');
ylabel('Signal Manitude');
subplot(4,1,2);
stem(n, pha);
title('Phase of exp\^(-0.2+0.5j)*n Signal');
xlabel('Sample Number');
ylabel('Signal Phase');
subplot(4,1,3);
stem(n, re_part);
title('Real part of exp\^(-0.2+0.5j)*n Signal');
xlabel('Sample Number');
ylabel('Signal Amplitude');
subplot(4,1,4);
stem(n, im_part);
title('Imaginary part of exp\^(-0.2+0.5j)*n Signal');
xlabel('Sample Number');
ylabel('Signal Amplitude');