n = input('Enter a time interval...');
x1=cos(2*pi*0.5*n); 
x2=cos(2*pi*0.5*n);
result = x1 + x2;
subplot(3,1,1);
plot(n, x1, 'linewidth', 2);
xlabel('Time Interval');
ylabel('Amplitude');
title('Signal x1');
subplot(3,1,2);
plot(n, x2, 'linewidth', 2);
xlabel('Time Interval');
ylabel('Amplitude');
title('Signal x2');
subplot(3,1,3);
plot(n, result, 'linewidth', 2);
xlabel('Time Interval');
ylabel('Amplitude');
title('Signal resultant');
