pha1 = input('Enter first signal phase shift....');
pha2 = input('Enter second signal phase shift....');
x1=2*cos(4*pi*0.5*t + pha1);
x2=2*cos(4*pi*0.5*t + pha2);
resultant = x1+x2;
subplot(3,1,1);
plot(t,x1,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title(sprintf('Cosine wave, Freq = 4 HZ, Amp = 2, Pha = %i RAD', pha1));
subplot(3,1,2);
plot(t,x2,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title(sprintf('Cosine wave, Freq = 4 HZ, Amp = 2, Pha = %i RAD', pha2));
subplot(3,1,3);
plot(t,resultant,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title('Resultant of both signals');
