fre1 = input('Enter frequency for first signal....');
fre2 = input('Enter frequency for second signal....');
t=-2:0.01:2;
x1=2*cos(fre1*pi*0.5*t);
x2=2*cos(fre2*pi*0.5*t);
resultant=x1+x2;
subplot(3,1,1);
plot(t,x1,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title(sprintf('Cosine wave, Freq = %i HZ, Amp = 2, Pha = 0RAD', fre1));
subplot(3,1,2);
plot(t,x2,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title(sprintf('Cosine wave, Freq = %i HZ, Amp = 2, Pha = 0RAD', fre2));
subplot(3,1,3);
plot(t,resultant,'linewidth',3);
grid;
ylabel('Amplitude');
xlabel('Time');
title('Sum of two cosine signals');
