n = -10:0.1:10;
x1 = 5*exp(1i*n*pi/4);
x2Ga = 2.7.^n; 
x2La = 0.4.^n;
xm1 = x1.*x2La; xm2 = x1.*x2Ga;
subplot(2,2,1);
plot(n, real(xm1), 'linewidth', 2);
title('Real part of Signal for 0<a<1');
xlabel('n');
ylabel('Amplitude');
subplot(2,2,2);
plot(n, xm1, 'linewidth', 2);
title('Exponential Signal for 0<a<1');
xlabel('n');
ylabel('Amplitude');
subplot(2,2,3);
plot(n, real(xm2), 'linewidth', 2);
title('Real part of Signal for a>1');
xlabel('n');
ylabel('Amplitude');
subplot(2,2,4);
plot(n, xm2, 'linewidth', 2);
title('Exponential Signal for x>1');
xlabel('n');
ylabel('Amplitude');
